name: Build and Publish Helm container

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Helm container
      uses: docker/build-push-action@v1
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ secrets.DOCKER_USERNAME }}/k8s-helm
        add_git_labels:  true
        tag_with_ref: true
        push: false
    - name: Test Helm container
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: GIT_BRANCH=${GITHUB_REF#refs/heads/} make test
    - name: Publish Helm container
      if: ${{ startsWith(github.ref, 'refs/heads/m') || startsWith(github.ref, 'refs/heads/v') }}
      uses: docker/build-push-action@v1
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ secrets.DOCKER_USERNAME }}/k8s-helm
        tag_with_ref: true
        add_git_labels:  true
        push: true
